import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    width: '100%',
    height: 209,
    backgroundColor: '#2D383E',
    position: 'absolute',
    bottom: 10,
    borderRadius: 16,
    justifyContent: 'space-evenly',
  },
  topButtons: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  documentContainer: {
    width: 52,
    height: 52,
    borderRadius: 50,
    backgroundColor: '#5157AD',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  cameraContainer: {
    width: 52,
    height: 52,
    borderRadius: 50,
    backgroundColor: '#D3396D',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  galleryContainer: {
    width: 52,
    height: 52,
    borderRadius: 50,
    backgroundColor: '#AD46CD',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  audioContainer: {
    width: 52,
    height: 52,
    borderRadius: 50,
    backgroundColor: '#EE7B08',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  locationContainer: {
    width: 52,
    height: 52,
    borderRadius: 50,
    backgroundColor: '#019D54',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  contactContainer: {
    width: 52,
    height: 52,
    borderRadius: 50,
    backgroundColor: '#0796DC',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  text: {
    color: '#9CA5AC',
    fontSize: 14,
    fontWeight: '400',
  },
});
